// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MSNumpressFSharpConsole")>]
[<assembly: AssemblyProductAttribute("MSNumpressFSharp")>]
[<assembly: AssemblyDescriptionAttribute("F# port of the MSNumpress library.")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MSNumpressFSharpConsole"
    let [<Literal>] AssemblyProduct = "MSNumpressFSharp"
    let [<Literal>] AssemblyDescription = "F# port of the MSNumpress library."
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
